apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: builder-runtime
  namespace: peep
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/component: backend
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: builder-runtime
  namespace: peep
  labels:
    app.kubernetes.io/name: builder
    app.kubernetes.io/component: backend
subjects:
  - kind: ServiceAccount
    name: builder
    namespace: peep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: builder-runtime
