apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peep
resources:
  - namespace.yaml
  - secrets.yaml
  - configmaps.yaml
  - postgres.yaml
  - redis.yaml
  - api.yaml
  - builder.yaml
  - dashboard.yaml
  - nginx.yaml
  - ingress.yaml
